spring.application.name=urlshortener
# Banco de dados
spring.datasource.url=jdbc:postgresql://localhost:5432/urlshortener
spring.datasource.username=postgres
spring.datasource.password= ${MINHASENHA}

# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# Flyway
spring.jpa.properties.jakarta.persistence.schema-generation.database.action=none
spring.flyway.enabled=false