spring.application.name=urlshortener
# Banco de dados
spring.datasource.url=jdbc:postgresql://localhost:5432/urlshortener
spring.datasource.username=postgres
spring.datasource.password= ${MINHASENHA}

# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# Flyway
spring.jpa.properties.jakarta.persistence.schema-generation.database.action=none
spring.flyway.enabled=false

#JWT
jwt.secret=${JWTSECRET}
jwt.expiration=86400000

#REDIS
spring.data.redis.host=localhost
spring.data.redis.port=6379

cache.url.ttl=3600

# RabbitMQ
spring.rabbitmq.connection-timeout=5000
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# Nomes da fila e exchange
rabbitmq.queue.url-access=url.access.queue
rabbitmq.exchange=url.exchange
rabbitmq.routing-key=url.access